[project]
name = "odoo-addons-open-synergy-ssi-web"
version = "19.0.20260719.1"
dependencies = [
    "odoo-addon-ssi_web_clear_all_filter==19.0.*",
    "odoo-addon-ssi_web_edit_attachment_name==19.0.*",
    "odoo-addon-ssi_web_login==19.0.*",
    "odoo-addon-ssi_web_sticky_list_header==19.0.*",
    "odoo-addon-ssi_web_widget_ace_git==19.0.*",
    "odoo-addon-ssi_web_widget_csv_table==19.0.*",
    "odoo-addon-ssi_web_widget_json==19.0.*",
    "odoo-addon-ssi_web_widget_many2onereference_clickable==19.0.*",
    "odoo-addon-ssi_web_widget_whatsapp==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
